name: "BlackPaw Nomad Manager (Edge)"
slug: "blackpaw_nomad_manager_edge"
description: "Development channel (latest build from main)"
version: "edge"
arch:
  - amd64
  - aarch64

image: "dockerhubuser/blackpaw-nomad-manager-{arch}:edge"

ingress: true
ingress_port: 8099
